### ISSUE TITLE
Fast-Forward pigs and junimos when you go to bed in that day. Would be a perfect mod for endgame.

### ISSUE THREAD

**Issue by JAWSAWN** [StardewModders/Modding-Ideas#103]
The thing that bugs me in the endgame is the wait you have to wait for truffles and junimos. In the endgame where you only want money its such a chore. So why not fast forward their activities for the rest of the day when you go to bed! 
That would make the endgame way more fun. Also combined with Automation mod it would give the perfect automation results. 

Edit: Also lightning rods could use that feature aswell. They all would fill up without destroying the crops.

**Comment by Platonymous** [comment]
[Uploading PYTK_0_8_4b_SleepWorker_1_0_0b.zip…]()
Try this and let me know if it works.

Skipping time freezes the game for a moment, and skipping past 19:50 will greet you with an "It's getting late" message in the morning. I might find a better solution down the road, but for now the default settings are set to skip 5h max and not past 19:50. You can change them in the config.json if you want to skip longer or more hours.

**Comment by Platonymous** [comment]
https://www.nexusmods.com/stardewvalley/mods/2062/
