### ISSUE TITLE
Hunger 1.3

### ISSUE THREAD

**Issue by RyuuInu** [StardewModders/Modding-Ideas#111]
I feel as if the food aspect of Stardew Valley is very lacking... What’s the point of cooking food if it isn’t even necessary? Food should be necessity to maintain stamina. If you don’t eat you lose stamina quicker and or don’t have any at all! Also adding a new mail person to send food sometimes would be cool (before you get a house with a kitchen)

**Comment by RyuuInu** [comment]
I know others have done this, but I’d LOVE to see a new one for 1.3 and for it to work well with CP!

**Comment by RyuuInu** [comment]
This mod has been uploaded by Yyeahdude on NEXUSMODS. Simply look up “Hunger Mod”

**Comment by TehPers** [comment]
For reference: https://www.nexusmods.com/stardewvalley/mods/613/
