### ISSUE TITLE
Economy Splitting Mod

### ISSUE THREAD

**Issue by uhmako** [StardewModders/Modding-Ideas#119]
This is just an idea I had. I know that Stardew Valley multiplayer is promoting the act of working together and building a joint farm, but there is the option to separate the cabins. If there is an option to separate the cabins, there should be an option to separate the money! So here is the idea.

- Make the mod compatible with the mods that allow unlimited players/cabins (like the Unlimited Players mod by "Armitxes")

- When each new person joins, they start with 500g, like you would in single player.

- When people sell things, then it goes to their OWN wallet instead of everyone else's wallet. 

The reason that I bring this up, is because when you play with a lot of friends, you may run into the problem that one farmer is doing more work than another farmer, and the farmer doing less work is spending money they didn't "earn." What my friends and I were doing was writing down exactly how much we sold each day, and logging it as if we were doing a statement. At the end of each day, in our little google docs or whatever we were using, we would do X amount of gold/Total amount of gold.

Instead of it being so complicated, it would be a lot easier if we all made our own money instead of it going into a joint account. It makes it harder to save up for stuff if your friends are spending money and you want to buy something that is relatively expensive early on (like an Iridium Rod.) This is just an idea to think on, so if anyone is down to develop it then that would be awesome! I might even be down to fund a mod like this, as long as it was successful and maintained!

**Comment by hawkfalcon** [comment]
I looked into this, it wouldn't be as hard as I expected. It isn't trivial, though, and *every player would need to have this mod*

For whoever ends up doing this:
Farmer holds a reference to FarmerTeam, which currently tracks money. All that would be needed is to modify Farmer to use your mod's money storage in addition (or instead). It would need to keep track of everything the current player puts in the selling chest, and at the end of the day calculate just those. 
The mod would have to be responsible for separately saving the current players wallet balance, as only the host player currently saves the money amount.

**Comment by Platonymous** [comment]
https://www.nexusmods.com/stardewvalley/mods/2303

**Comment by Littlebigdough** [comment]
hello this might be irrelavent but i just want to add for anyone veiwing this in the present that the offical multiplayer now has an option to seperate money and you dont have to use a mod :))
