### ISSUE TITLE
Gem slots for Iridium Tools

### ISSUE THREAD

**Issue by FenixR** [StardewModders/Modding-Ideas#120]
Had this idea a while ago, how about making Gems (Or if you are masochistic enough, the rocks gotten from geodes) to be embedded into Iridium Tools like fish lures (With a 100-200 use limit possibly?) for additional effects, some would include:

- 2 x Range
- Stamina consumption set to 1
- Infinite water for watering can, more wood for axe, better chance of items from hoe/pickaxe.
- Instant Tool Charging
- Magic Hands for the cursor to use the tool in a far away area
- etc

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/3090/
