### ISSUE TITLE
Randomized gift tastes on a per save basis

### ISSUE THREAD

**Issue by Awwhri** [StardewModders/Modding-Ideas#121]
It'd be pretty cool to have a mod that changes the gift tastes of each villager for each save file.

As a maybe more complicated request, it'd be cool to have the gift tastes randomized from a set list of preferred gifts personalized to each villager every day. I know I wouldn't like to get the same two things constantly from someone, it'd get pretty stale.

**Comment by moriczgergo** [comment]
Should this ignore all universal tastes?

**Comment by skuldomg** [comment]
I had the same idea a couple of weeks back but thought it was a bit stupid and there wouldn't be any demand. But if @moriczgergo has it basically ready, you can also go ahead and make it standalone :)

**Comment by Awwhri** [comment]
Yeah, I think universal tastes are probably best left alone.
