### ISSUE TITLE
Adjustable Heart Requirements for Flower Festival Dance Partner

### ISSUE THREAD

**Issue by KnittingCounter** [StardewModders/Modding-Ideas#122]
Hey all! I'm a big  fan of @spacechase0 awesome Three Heart Dance Partner. I used to play with it all the time so I could bamboozle Shane into dancing with my sorry, smelly farmer, hehe. I'm not sure if the mod still works on the latest beta of the game or if it will work once that version's released (I assume SMAPI will get an update by then as well), so I figured I'd ask here if maybe someone could make a variant that's configurable?

Here is the original repository, where @spacechase0 has kindly offered the source code for the mod.
https://github.com/spacechase0/ThreeHeartDancePartner

An alternative version where we could use a config file to choose how many hearts would be required would be flippin' amazing! I just love this event - one of my favorites, and who in Pelican Town wouldn't want to join in the fun dancing with the newcomer farmer? Nobody, that's who! 

Or... at least a version where only one heart is required would work as well... :P

Fingers crossed someone may be able to throw this together, that would be amazing! Thank you in advance! :)

**Comment by Pathoschild** [comment]
Since the mod is open-source, it'd be easy to submit a pull request to make the number configurable.

**Comment by KnittingCounter** [comment]
Woo! All appendages crossed that someone may be able to give it a go :smiley:

**Comment by Mizzion** [comment]
If you want an unofficial update to this mod. You can get it https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/page-14#post-3286198

The unofficial updater sent in a PR aswell.

**Comment by KnittingCounter** [comment]
Woo, thank you so much for the update with the config file! You're the best! :)
