### ISSUE TITLE
Craftable Sign with Text

### ISSUE THREAD

**Issue by TheRaven81** [StardewModders/Modding-Ideas#123]
Would cost the same materials as the existing signs to craft. The sign would be able to be placed anywhere the existing sign can.
**Usage Process:**
- Craft sign from Crafting menu,
- Place sign down wherever able, 
- Once placed, an interface created by SMAPI will pop up asking for text input for what the sign will say, with an OK button below the text entry field to press once the user is finished.  Text box for text input should allow for multiple lines, and have a character limit of 100. 
- Once you press the OK button, then you can hover your mouse cursor over the sign, and a little tooltip-style popup will appear, containing the text of the sign. The character limit of the input interface will prevent this pop-up from getting too big to see the entire text.
- The text entered is permanent unless the sign is picked up, then the text is erased.

These are a few mockup designs I made for the signs, from the sign sprites on the Craftables sheet(blown up by 400% to represent actual in-game size).
![text sign mockup sheet](https://user-images.githubusercontent.com/676345/40664474-0151ef24-6329-11e8-9576-f0127110c87f.png)

**Comment by Platonymous** [comment]
A bit different than what was suggested but the same idea:
https://www.nexusmods.com/stardewvalley/mods/3068
