### ISSUE TITLE
Outdoor hot springs

### ISSUE THREAD

**Issue by thatnzguy** [StardewModders/Modding-Ideas#124]
The Hot Springs building has an outdoor pool you can walk into without going inside for easy access

**Comment by saewill** [comment]
Immersive Farm 2 has one, I highly recommend it: https://www.nexusmods.com/stardewvalley/mods/1531

**Comment by Riazaia** [comment]
Someone made this! )))
https://www.nexusmods.com/stardewvalley/mods/2751
