### ISSUE TITLE
All The Small Things.

### ISSUE THREAD

**Issue by TiredPoison** [StardewModders/Modding-Ideas#132]
I don't know what difficulty this would be as many of the things I list vary in difficulty and it would need textures. (I would **prefer** if most of these things were in an all in one mod with a config to disable and re enable parts of the mod so it appeals to everyone. It doesn't have to all be released at once its just preferable for me as a simple package me and all my friends can have on our server.) Enough with me rambling lets get to the things!

Watering Can Refills -  While it is raining as long as your watering can is in your inventory it refills over time!

Ore Chances - Normal boulders and rocks have a small chance to yield some copper or quartz with a lesser chance of iron.

Witch Pumpkin event -  A witch flys over night and makes one of your pumpkin plants grow a golden pumpkin!

Scary sprinkler! - A sprinkler and a scarecrow combined so it fits all in one plot, sprinkler distance depends on what sprinkler you crafted it with (Don't know if you can check for that or if you want to make several versions or make one with a iridium sprinkler its up to you!)

Ground Sloth - This one by far is probably by far be the most difficult but by far my favorite. The way I think it could be implicated is if you complete a difficult community center bundle that rewards you with a sloth egg (Shhhh its a mystery egg and no one knows why its an mammal in an egg its just junimo magic) The next morning robin mails you a letter saying she heard about the egg and that she can build a special building for it to incubate in as it is rather large, in 5 days after the building is built and in another 10-15 days the egg hatches and a Ground sloth can be rode but it does something special...It has its own energy bar that can be used to clear rocks and debris rather quickly,

(I am mostly new to stardew and github so if there is things already added I am happy to renew them)
I will add more to this list most likely but a few things,I know nothing about modding so if something isn't possible I will remove it, I don't know how to add the tags but it clearly needs smapi and textures. The goal of this list **mostly** consist of small additions that just breathe alot of life into stardew and make it more convenient hence the name I gave it "All the small things" or ATST for short.

**Comment by Entoarox** [comment]
Please make separate issues for each idea, no matter their scope - this is for sorting and management reasons.

**Comment by TiredPoison** [comment]
My bad I just didn't want to clutter this place. :)

**Comment by KarBoy2314PL** [comment]
#239 #240 #241 #242 #243
