### ISSUE TITLE
Headless multiplayer server

### ISSUE THREAD

**Issue by TiredPoison** [StardewModders/Modding-Ideas#133]
Was wondering if there was a unofficial way to host a server in a sense. Have a farmer host a map and make him auto sleep (with mods or a macro bot), and then have time not pass until a farmhand joins then time passes and freezes when he leaves. The only issue I can see but I wouldn't mind is if there is an even that requires all the players be there and possible have the player automatically warp to their locations with some work and boom a 24/7 server hosted that way me and a few friends can just hop on with the join code.

End result: A game hosted on a computer that has the main farmer frozen in time until a farmhand joins.

I have a server with a lot of friends and sometimes they ask for me to hop on when I want to play a different game or something.

**Comment by Entoarox** [comment]
Until SDV 1.3 leaves beta something this involved would likely be a nightmare to maintain, if it is even doable in the first place, as the MP wasn't designed for a situation like this.

**Comment by Caraxi** [comment]
So... I did it, It's dirty, but I seem to have done it...

I've made a mod that does the following

**On Game Start:**
 - Launch into predefined save in multiplayer hosting

**When No Farm Hand is Online:**
 - Pause the world (/pause)

**When a farm hand is online**
 - Unpause the world

**When all farm hands are sleeping**
 - Warp the main client to bed if they're not already
 - Put the main client to sleep, ending the day
 - Exit the daily earnings screen

It needs some testing and there is some things that will very likely break it, but it seems to be in general, working

**Comment by funny-snek** [comment]
It is done! https://www.nexusmods.com/stardewvalley/mods/2677
