### ISSUE TITLE
Longer lasting fishing lures

### ISSUE THREAD

**Issue by siramikvarse** [StardewModders/Modding-Ideas#136]
Hi I really think the game needs stronger fishing lures, if you go fishing for a whole day you have to take an inventory full of lures and attach a new one every five minutes.

I think this is really lame but I cant find a mod to change this to my preferences, the mod should probably have several settings to make everyone happy but I think they should last five times longer to be worth using, it should be pretty easy to do and I looked into what it would take to change it myself but my ability stops at total war and skyrim modding (and that's because they have easy to use help).

So I would really like it if someone else could come along and make this, I'm sure lots of other people would like this mod as well it should be popular

**Comment by Caraxi** [comment]
I did the thing. Is configurable for both default uses and allows defining a number of uses to add for every level of fishing skill. Let me know if there is some other configuration you'd like

https://www.nexusmods.com/stardewvalley/mods/2510
