### ISSUE TITLE
Remember slot order

### ISSUE THREAD

**Issue by gogshow** [StardewModders/Modding-Ideas#137]
I would like to suggest a mod where I can choose where my items stay in HOTBAR.

PS: Configurable.

Example: I always put my hotkey like this:
1 - SWORD
2 - PICK
3 - ENXADA
4 - COFFEE
5 - OTHER MEALS
6 - ORES
7 - PUMP
8 - MEGA PUMP
9 - TELEPORT.

The player simply clicks on the ORGANIZE icon and the items will return to the positions that have been configured.

**Comment by Pathoschild** [comment]
It's up for grabs, but nobody has officially claimed it yet. It'd be a useful mod though, so I think someone will create it eventually.

**Comment by gogshow** [comment]
Up

**Comment by Riazaia** [comment]
[Better Sort](https://www.nexusmods.com/stardewvalley/mods/1992) can do that? I think?
