### ISSUE TITLE
Only effect the tile you actually clicked

### ISSUE THREAD

**Issue by logan97alexander** [StardewModders/Modding-Ideas#138]
I really hate how if you use a tool on a tile that's just _slightly_ out of reach, instead of having no effect, it reroutes your tool to a closer tile-- potentially destroying crops or impacting tiles you didn't want impacted. If I'm one pixel over the line and I hoe a tile I didn't realize counted as "underneath" me, I don't want it to hoe some other nearby tile, y'know?

**Comment by Pathoschild** [comment]
[Extended Reach](https://www.nexusmods.com/stardewvalley/mods/1493/) does that. :)
