### ISSUE TITLE
Make mixed seeds truly random

### ISSUE THREAD

**Issue by theghostlymeow** [StardewModders/Modding-Ideas#159]
I feel like mixed seeds are not living up to their full potential. Why aren't they truly random? My mod suggestion is to make mixed seeds truly random with a full selection of season-appropriate crops, with the greenhouse being truly random and not limited by season.

**Comment by megmom84** [comment]
Yep mixed seeds should have a possiblity to grow out any crop that is appropriate for the current season but it seems like in the spring I only get parsnips and the occcasional cauliflower or potato. never green beans, jazz, tulip or kale.

I think there could be an alternate version even where the mixed seeds could possibly grow out appropriate json assets crops if that mod is installed

**Comment by EpicBellyFlop45** [comment]
https://www.nexusmods.com/stardewvalley/mods/3012 Enjoy :)
