### ISSUE TITLE
Cat Gifts

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/Modding-Ideas#16]
There isn't enough iridium-quality cream in the world to get a cat to work for you, but that isn't to say that cats do nothing but doze all day and sleep all night... For one, cats keep many pests at bay on your farm.

And secondly, once you're good friends with your cat, they might find it in themselves to bring you a memento from their nightly roam! Don't expect to see a gift every morning, but also don't be alarmed if one of the following items unexpectedly shows up at your front door:
- Duck Egg, Duck Feather, Wool, Rabbit's Foot
- Purple Mushroom, Void Egg, Bug Meat, Bat Wing, Wild Bait
- Periwinkle, Snail, Bait, Shrimp
- a geode, a precious mineral, Coral
- a seasonal seed, a seasonal forage berry or fruit
- an odd, dirty doll
- a note bearing only a tiny, bloody pawprint (wait)

**Balance etc:**
- sort items to weighed tiers, more likely to get lower tier gift
- no consecutive top tier gifts
- weekly limit to gifts
- possibly include some (new?) trash/useless items.

**Comment by skuldomg** [comment]
Nice idea, I'm working on it :)

**Comment by skuldomg** [comment]
Released! Thanks for the idea.
https://www.nexusmods.com/stardewvalley/mods/2132

**Comment by TehPers** [comment]
This should probably be closed as it's completed.
