### ISSUE TITLE
Many suggestion for  mods.

### ISSUE THREAD

**Issue by GhostLegionnary** [StardewModders/Modding-Ideas#166]
Helllo ! I am a French player and I started to play this game a week ago.

I have ideas. Give my opinion!

(ps: it is my first post on reddit, If I make a mistake, be kind.)

I: More negative event.

Like: flood, forest fire, storm, insect invasion on your crops.

I found the life in stardew valley too easy, and too nice. I think some bad things can be done at the challange level of this game, and make interesting situtation.

That even can touch you, or another villager. In this situation you can give your help to other NPC (whit friend bonus of course) but that can take a lot of time and energy.

In returne, If you make good action, and are a friend whit other villager, You can get help it if you have a problem. (help for fixing the damage on your farme.)

For example, afther a storm, the shops can be closed for repairs,and you can visit the NPC and give your help for clean or repaire ( and that can give work for Robin )

I think it's in the spirit of this game, the mutual help is important in this game.

The insect invasion can be a special problem, whit 3 thing:

do noting, but you can loose a % of your crops, and the value of your product down ,

or you can use some organic insecticide, that have 50% of success (and kill all of the insect), and 50% to reduce to half the problem.

And the final solution it's buy heavy chemical product in jojasupermaket, that are very supper effective, but that makes a bad opinion of you on the city, and that has a littel probability to poison your self (whit energy malus on the start of the day)

II: More NPC interaction and situation

The NPC can interact more often whit more animation bewteen them

And we could have special interactions in this situation, in this situation, you can make different choices, some times it's Cornelian choices.

For example, you can take the defense of a villager, but the other villager can take that bad, you will sometimes choose who support

III: More furnitur

I think it can be a good thing if we can go to the carpentery, and order a product like a chair, or a sofa, whit specific color, type of wood ect ....

More you spend money or time in relation to your carpenter, more the product can be great and more choise you can get

IV: More destination

That can be so cool, like moutain, tundra.

You can imagine the same thing whit boat on some island.

Whit of course, unique event, unique objet (and why not honneymoon)

V: Better fight

More type of weapon, more stuff can be wear (armor, glove ...)

More technical of combat, more buff, more type of enemy, and more different type of dungon like creep, cave of yeti, or goblin.

And the most important thing, the possibilty to invite NPC like follower. All of NPC can have specific weapon and style combat, can give buff or heal you.

Aibigail can use sword and make a lot of damage, Maru use energy weapon ect .....

all of NPC cannot follow you on your aventure of course (Mayor, Wizard, Robin ....)

VI: Price change

The price of your product can change for the time being, for example, the pumpkin can be sold for more the day before the fall festival.

The price of wood can double afther fire in the forest.

And of course If you sell too many of the same product, that price can be down. to compensate the player can transform this product, or cultivate more different thing.

VII: Agrosystem concept

Very important idea.

For my it's important on this game, for example have some sheep or cow can incrase the quality of soil.

You can make composter, and product compost to improve the quality of your soil.

Cultivate different types of crops.

That can be good to cultivating wheat and bean

The quality of soil can be an important thing. you can improve it if you give to the soil, or you can compost on it.

It's all. Give me your opinion

**Comment by Entoarox** [comment]
Please separate your suggestions into separate issues, this makes it possible for each of them to be separately tagged and, if completed, identified such.
