### ISSUE TITLE
Custom Crops

### ISSUE THREAD

**Issue by AmburrBambii** [StardewModders/Modding-Ideas#17]
Create a base mod that works similar to Custom Farming. Adding crops would be easy peasy lemon squeezy!

**Comment by pcsbx** [comment]
So a mod/resource that lets you input a tileset and the strings and numbers for a crop, and whip up a ready-to-use mod from those?

Is it feasible to also manage custom crops with this, to tweak properties, update graphics, and if needed disable/able/remove crops?

**Comment by AmburrBambii** [comment]
Absolutely! User friendly, easily add or remove crops you want or don't want, with no XNB fiddling.

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/1592/
