### ISSUE TITLE
request: Mod that has the game request select files that normally load upon game startup at specific intervals

### ISSUE THREAD

**Issue by FoggyWizard** [StardewModders/Modding-Ideas#175]
Such as NPCdispositions, Schedules, and whatever else would normally load at the beginning of the game. To allow for Content Patcher to make conditional changes to them, like a character's name changing after an event, or a character being conditionally dateable (like if a mod ages up a character over time, and they wouldn't originally be datable because they're too young at the beginning of the game, or if someone wanted to impliment and NPC divorce mod).

**Comment by Entoarox** [comment]
This is pretty much infeasible even with SMAPI handling the content manager, simply put, the files are loaded when the game needs them, not any sooner, not any later.

Mods are provided the ability to force these files to be disposed at any point, causing the game to reload them the next time it needs them.

So your suggestion is a technical impossibility, as most of the games files arent loaded during startup, but whenever the game happens to first need them.
