### ISSUE TITLE
forever growing grass from grass starters

### ISSUE THREAD

**Issue by Pookachutf** [StardewModders/Modding-Ideas#194]
I like to build large animal farms where I easily have over 100 animals; which being the creatures they are eat grass 3 seasons out of the year. What I don't like about having this large of an animal farm is the fact I have to freeze time and plant over 1000 grass starters every few days.

What I would love is a mod that would make it so I never have to plant grass again after doing it the first time (options for grass removal via scythe in case you dont like where you planted it).  Also it should work with the Winter Grass mod https://www.nexusmods.com/stardewvalley/mods/1601)

**Comment by minervamaga** [comment]
Whoops, here's the unofficial update: https://community.playstarbound.com/attachments/181725

**Comment by Entoarox** [comment]
Marking this complete, as a mod for fixing grass growth capability already exists.
