### ISSUE TITLE
End Marnie's Hay Racket

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/Modding-Ideas#24]
Extract hay from the silo/hopper even when there is no space on the feeding table. Preferably with the same "hold for more" mechanic as is with vanilla hopper functionality.

and/or

Enable hay drops to inventory when mowing whenever there is 1 or more silos, but no free silo space.

**Comment by danvolchek** [comment]
I've done this! I added both the hay extraction with "hold for more" mechanic and getting hay from grass if you don't have any free silo space, or don't have any silos. Let me know if you want any changes made :).

You can find the download [here](http://www.nexusmods.com/stardewvalley/mods/1430/?)
You can find the source code [here](https://github.com/danvolchek/StardewMods/tree/master/BetterHay)
