### ISSUE TITLE
Persistant Grass in winter

### ISSUE THREAD

**Issue by Oakwooooood** [StardewModders/Modding-Ideas#28]
Greetings everyone, as I am making a lot of decoration with grass it's tiring to place it all again each year. Now that my farm is near completion it takes me 3 WHOLE DAYS and almost an entire stack of grass starters to redo it each time.
I really like tall grass, I live in the deep countryside of france and there are places with that kind of wilderness.
A project I had was to decorate the whole game with grass to make it rich in details but if I have to put it all again each year it's gonna be impossible.

So I was wondering if there are people in the same case ? I was looking for that kind of mod for a long time but I never saw something similar. The most tiring part is to put the grass that I like to place under items like fences, bee hives or lightning rods.

Something really optimal would be a mod that keep the grass in place during winter (of course the grass is invisible in winter). Also it's not breaking any immersion, on the contrary it makes more sense that grass does not die during winter as it usually goes dormant beneath a layer of snow.

I don't really know how it works here, please advise on how to make this kind of request.
Thanks, Oak.

**Comment by Katknapp** [comment]
I am also very VERY interested in this for all the same reasons as the requester. I use grass aesthetically as well. ALOT of it. I would like for it to either remain brown grass or a snowy white grass that DOES NOT grow. (If it was invisible, that would be fine too) Maybe config. options would be possible?

It would also be helpful to have a way to retrieve grass starters from the hoe, scythe, or pick similar to how that the mod "[better hay](https://www.nexusmods.com/stardewvalley/mods/1430/?)" behaves with a chance to drop grass starters. In farming, it just makes sense.

All I know is, we need a "Better Grass" mod. Thanks for considering!

![screen shot 2017-10-16 at 9 42 46 am](https://user-images.githubusercontent.com/14977930/31620188-9b7031d6-b264-11e7-9b30-0db6f9bb29af.png)

**Comment by Katknapp** [comment]
I found a grass file that has bluish hue grass at chuckles for idea basis (credit: [Maleha])(https://community.playstarbound.com/threads/a-whole-bunch-of-things-pets-paths-stable-etc.111044/)
![screen shot 2017-10-17 at 10 47 45 am](https://user-images.githubusercontent.com/14977930/31671936-21bf3f74-b329-11e7-9e9e-0c60610817e9.png)

**Comment by Oakwooooood** [comment]
Thank you for the support, I'm desperately waiting for someone to take this little project on to continue my farm :( It's really blocking me from continuing my decoration frenzy :/ +1 for the chance to drop grass starters, it would add more realism.

**Comment by Oakwooooood** [comment]
Even if there the grass stayed invisible in winter, it would still make sense as grass is normally dormant underneath the snow layer in winter but I wouldn't mind beautiful frozen grass.

**Comment by Katknapp** [comment]
Thanks Oakwood, yes, it's been driving me crazy, I wish I could code! ^^ I'm glad I'm not alone!

**Comment by JustABallaG** [comment]
Interested in this one. I'm a novice to intermediate programmer so it would take a while for me. If anyone else wants to help me out they can PM me.

**Comment by JustABallaG** [comment]
@Katknapp and @Oakwooooood should PM me on Discord JustABallaG#2788 so we can chat! Honestly will probably take me months but I'm willing to put in the work.

**Comment by Oakwooooood** [comment]
Hey @JustABallaG thank you so much for caring for this!!! I'll surely send you a message right when I have time (which is now hahaha)

**Comment by danvolchek** [comment]
Hey there @Oakwooooood and @Katknapp, I'm the creator of the Better Hay mod. Thanks for using it!

Regarding the grass starters dropping from grass - I can add that as a config option to the Better Hay mod. Maybe a number you can set from 0 to 100 % indicating the chance of dropping a grass starter instead of hay? Or maybe just a value that is true or false that changes all drops to grass starter? Keep in mind that in the case that a grass starter drops, nothing would be added to the siloh. If there's a better way of adding this, please let me know your ideas!

Regarding grass in winter, would you just not want grass to go away on the first day of winter? The game spawns in stones and weeds and stuff on the first day of winter which take the place of some grass spots - would you want that to still happen? I.e. some grass would be changed to stone, but not all of it would die.

Keeping grass around in winter seems easy and I can do it - barring unexpected issues or complexity that comes up.

**Comment by Oakwooooood** [comment]
Thank you @danvolchek for answering here!! @Katknapp was suggesting that grass starters could be harvested from grass using the hoe but maybe it's too difficult to code that ? This way you can choose if you want hay or grass starters. Setting a percent of dropping would perhaps annoy someone who want to prepare for winter and changing the number in the config file would break the roleplay but it's a solution nonetheless!

My main concern for this request was the grass to stay in winter, as I explained, I do a lot of decoration with grass and it's tiring to put it up again each year. As for the weeds, couldn't the gold clock block it ? but yeah even if there are some stones and bushes it would be reaaaally better than nothing.

**Comment by Katknapp** [comment]
@danvolchek - Well the main mod discussion here is really for "grass to remain in winter" as priority. (hopefully with the use of the blue grass sprite) 

I thought a grass starter drop would be useful in an addition to that and something I always wanted. I didn't think about balance as far as people using it to basically harvest grass for money, lol. I wouldn't personally use it that way, cos I just need grass. Perhaps, making this a low percentage drop would be best or even a customizable percentage (for people who don't care about game breakers). True/false setting for grass to drop should be there also for people who do not want this feature at all. I think it can be made reasonable and not immersion breaking if implemented correctly. I am against getting 100% grass starter OVER hay for instance, that wouldn't be fun for me, but maybe someone else, who am I to judge? 

If using scythe, getting no-hay-to-silo would be fine/fair for when the low chance of a grass starter would drop. Using hoe would be even better, but I worr, it will would actually hoe dirt spots, and that's undesirable. Not sure if its possible to bypass that with code when using hoe on grass versus on dirt alone.

I hope my thoughts are clear, sorry if not.

I'm available to test/contact at I'm Orchid#1492 on discord, if you use that. ;)

**Comment by danvolchek** [comment]
I'll continue the conversation on discord and post any major updats here!

**Comment by Oakwooooood** [comment]
Okay feel free to message me there!

**Comment by Katknapp** [comment]
This has been released and is working beautifully. Thanks @danvolchek.
https://www.nexusmods.com/stardewvalley/mods/1601?

Thread can be closed.

**Comment by danvolchek** [comment]
(@Entoarox)

**Comment by Entoarox** [comment]
Closed due to being implemented.
