### ISSUE TITLE
A mod idea for 'notes'

### ISSUE THREAD

**Issue by Tiessie** [StardewModders/Modding-Ideas#29]
Hello everyone, I came up with an idea for a mod. Does anyone else sometimes close the game and there's something you need to do that day, but the next time you start up the game you complety forgot about it? Well that happens to me ALOT and I thought of a mod that lets you make a note by pressing a key, for example N, and you can write what you wanted to do. The next time you boot up the game and wake up in your bed, a screen with what you wrote automatically shows up! I hope you like my idea.

**Comment by erik-hasse** [comment]
I've been working on a mod that lets you set reminders for an arbitrary date and time in the future. You could set a reminder for 6:00 the next day with your note!

I've got the basic functionality there, but there are a few more things I need to do before I'd be comfortable releasing it.

![hello world 1](https://user-images.githubusercontent.com/37126755/38847261-5e9971b8-41c6-11e8-9d6f-bbb73894d0a8.PNG)
![hello world 2](https://user-images.githubusercontent.com/37126755/38847262-5eaa47d6-41c6-11e8-9893-6e402a734933.PNG)

**Comment by Riazaia** [comment]
[Reminders](https://www.nexusmods.com/stardewvalley/mods/2481) and [To Do List](https://www.nexusmods.com/stardewvalley/mods/1630) ))
