### ISSUE TITLE
Journal glitch improvement

### ISSUE THREAD

**Issue by pcsbx** [StardewModders/Modding-Ideas#30]
Aim of this mod: add QoL to using Journal Glitch while staying faithful to the spirit of Vanilla time management (i.e. you're really not supposed to stay up after 2 am).

**Vanilla:**
- you have to click the journal icon every 10 in-game minutes to stay up, messing up workflow and potentially deadly in combat
- you cannot trigger the glitch via journal hotkey, and as such have to have a journal entry listed
- you can abuse the glitch to time travel for potentially limitless time 

**Modded:**
- no constant clicking, way more efficient use of time
- not dependent on journal content

Once the clock strikes 2:00 am you get a pop-up: _You feel very tired. Struggle to stay awake?_
- Yes -> you stay awake until you go to bed, or fall asleep by holding Z for a moment
- No -> you fall asleep

While staying up after 2:00 am, a "zzz" bubble marks every thirty minutes.

**To be decided**
How to handle mornings:
- hard limit at e.g. 5:00 am, or
- allow staying up indefinitely, but perform morning events only after sleep (go to sleep at 9:00 am -> morning events + wake up normally, except the time is 10:00 am)

(Optional/configurable/dynamic) penalty status effect for staying up after 2:00 am? During the night and/or the following day?

**Comment by Entoarox** [comment]
A mod that works like this already exists as http://www.nexusmods.com/stardewvalley/mods/1369/?
