### ISSUE TITLE
Traveling Cart - Visual makeover (with pig)

### ISSUE THREAD

**Issue by Rappeldrache** [StardewModders/Modding-Ideas#33]
Visual revision of the Traveling Cart (with the big pig, too). Not so colorful would be great. But ONLY a texture mod, so other game languages are not affected. 

Thanks. ;-)

**Comment by Acerbicon** [comment]
How about something like this? What are you wanting to change about the pig exactly?
![travellingcart](https://userimages.githubusercontent.com/18371051/30166390-348723e8-93b1-11e7-921d-a5a3616ae7b5.png)

**Comment by Rappeldrache** [comment]
Hey Ace, ouh I have no special idea. Just think the cart and the pig are TO colorful and a bit ugly. ;)

**Comment by Acerbicon** [comment]
How's this? https://drive.google.com/open?id=0B1l1v8XWIlpnLXFBMmx3U1NsNVk

**Comment by Riazaia** [comment]
done ))
https://www.nexusmods.com/stardewvalley/mods/2113
