### ISSUE TITLE
Craftable Flower Box

### ISSUE THREAD

**Issue by Rappeldrache** [StardewModders/Modding-Ideas#35]
Finishing this mod: https://community.playstarbound.com/threads/craftable-flower-box-decorations.109936/page-3
Copy from the thread: _"The flowers in this game aren't really worth planting (unless you're building a bee farm), but I enjoy the way they look. I thought I'd give a stab at creating craftable flower planters a-la the newer Harvest Moon 3DS games. This way they'd look pretty and give a reason to grow more flowers! As this mod is very much in-progress I'm open to suggestions."_

What a wonderful idea! It's NOT my thread. It's NOT my idea. :) I'm just a fan.

**Comment by Entoarox** [comment]
Marked both `smapi` and `xnb` as it might be possible to do this without SMAPI but I am not certain.

As it has been 10 months since the original creator last visited the SDV forums, I see no reason that someone else cannot pick up the idea to work on.

**Comment by Entoarox** [comment]
Updated to use the new `type: unknown` label

**Comment by Pathoschild** [comment]
[Garden pots](https://stardewvalleywiki.com/Garden_Pot) in the vanilla game let you do this now.
