### ISSUE TITLE
Strawdew Valley

### ISSUE THREAD

**Issue by Antoninko** [StardewModders/Modding-Ideas#44]
Strawdew Valley is a retexture mod that turns everything into straws and drinks . every character in the game is a straw except the wizard , who is an drink . i think the mod will be easy to do since it is a retexture mod , but i dont have the textures yet and dont know how to make them since im a newbie in the modding .

**Comment by Entoarox** [comment]
Uh, what? :confused: 

labeled `needs:information` with a extra dose of `needs:sobriety` since I feel like you wrote this drunk :astonished:

**Comment by ChefRude** [comment]
@Antoninko hey, Ive started messing around with straw sprites. Im working on Abigail. There are some issues.
look
<img width="339" alt="screen shot 2018-03-28 at 2 16 00 am" src="https://user-images.githubusercontent.com/19828854/38012068-0033d3fe-322e-11e8-804f-aa4d8741dfc6.png">
<img width="305" alt="screen shot 2018-03-28 at 2 16 26 am" src="https://user-images.githubusercontent.com/19828854/38012079-0c469294-322e-11e8-9217-24a0f3fba295.png">

Thats abigail WIP
but some of these special events will be hard to do.
<img width="271" alt="screen shot 2018-03-28 at 2 17 04 am" src="https://user-images.githubusercontent.com/19828854/38012100-20bb2c1c-322e-11e8-8bb5-36207d82955b.png">

**Comment by ChefRude** [comment]
@Antoninko [Resolved](https://www.nexusmods.com/stardewvalley/mods/2022)
