### ISSUE TITLE
Now bowlegs anymore

### ISSUE THREAD

**Issue by Rappeldrache** [StardewModders/Modding-Ideas#49]
Hello, a mod would be great where the characters have no bowlegs anymore. But this should be the only change.
So: Default characters only without the bowlegs. :-)

Thanks!

**Comment by pcsbx** [comment]
Abigail, Maru, Leah, Emily, Jodi
https://www.nexusmods.com/stardewvalley/mods/346/?

Harvey
https://www.nexusmods.com/stardewvalley/mods/879/?

Elliott
https://www.nexusmods.com/stardewvalley/mods/818/?

**Comment by Rappeldrache** [comment]
Done it myself  ;-)  : 
https://www.nexusmods.com/stardewvalley/mods/1500/?tab=1&navtag=https%3A%2F%2Fwww.nexusmods.com%2Fstardewvalley%2Fajax%2Fmoddescription%2F%3Fid%3D1500%26preview%3D&pUp=1

**Comment by Entoarox** [comment]
Per the work done by @Rappeldrache I am closing this and marking it complete

**Comment by Rappeldrache** [comment]
THANKS a lot @Entoarox  :)

For your great work here AND with all your mods. :) *Lot of Hugs*
