### ISSUE TITLE
Removing Crows / Infinite Scarecrow range

### ISSUE THREAD

**Issue by zanderb21** [StardewModders/Modding-Ideas#56]
Can anyone create such a mod?

**Comment by Entoarox** [comment]
Please reformat your title and post, a more complete and detailed description is expected in your post.

**Comment by zanderb21** [comment]
I do not know what you want me to say, I think the title is enough information, based on the context of the game. Anyone who played the game would know about crows, scarecrows and their limited range. I want a mod which either removes crows, or makes scarecrow range infinite. What more is there to say? The same for my other 2 requests, I think there is enough information provided based on the context of the game. Do you not know what a warp totem is, or a pet? Can you not understand that pets wander around their feed place, so if you change that place in the map, they will walk around in the original spot instead of the new one? All those things seem kind of obvious to me, and I would think especially to someone like you who is very advanced and experienced in programming, as your brain clearly is better than most people.

Speaking about your mods, you seem to have enough time on your hands to moderate my requests here, and pointlessly respond to me 6 times, so why do you not update your own mods, which constantly cause errors, or update them with the features I have requested, which seem quite useful and would make (or could have made, If I didn't have to scrap my ideas because of you) the experience of at least so far, 5500 people better and more immersive? Also seems kind of hypocritical of you to make your mods closed source when you are the one modifying a closed source game's code. If you are not willing to update your mods, make them public so people who are willing to, can do so.

Now, based on the downloads at the time for other mods such as "Custom Farm Types" and "Forage at the Farm" which both had around, or less than 100 downloads when I uploaded my first map and are listed in it's requirements, now both sit at over 6000, I think I can safely say your mods: XnbLoader, Entoarox Framework, Extended minecart have gotten the same amount of increased downloads. 

So why are you not showing me any respect here?
You never respond to my questions on the forum when I'm directly asking you for help or give a suggestion for new features, yet you have time to pointlessly ask me for what? How to make these mods? You're the programmer here you tell me. Do you honestly believe I would be asking here if I had any clue how you would go about making these mods? I'd be making them myself instead of wasting my time here responding to you.

**Comment by pcsbx** [comment]
so either
- disable crow spawning totally
or
- disable crow spawning if one or more scarecrows are in use on farm.

**Comment by zanderb21** [comment]
Yeah do you think you could make that? I have no idea how hard that would be

**Comment by danvolchek** [comment]
Hey @zanderb21, I've made a mod which removes crows entirely. Here it is: https://www.nexusmods.com/stardewvalley/mods/1682/?.
