### ISSUE TITLE
Warp Totem teleport change

### ISSUE THREAD

**Issue by zanderb21** [StardewModders/Modding-Ideas#57]
Can anyone create a mod which allows you to set a custom coordinates for the warp totems (specifically farm totem)?

**Comment by Entoarox** [comment]
Please reformat your title and post to clearly identify what your request is, how it is meant to work, and how related mechanics should be handled.

**Comment by zanderb21** [comment]
I have no idea what you're asking for mate

**Comment by Warilized** [comment]
@Entoarox I think it works like this:
- When using Warp Totem the mod will intercept its default coordinate 
- Then the mod will overwrite it with a custom-able coordinate (eg: Inside Player's house, at the center of the farm)
- Every Warp Totem have their own custom-able coordinates.

I think it handles the warp events coordinate to something else.
let says if "Farm totem" warps player to "Farm, coordinates: x, y" then the mood will overwrite it to something else, like this:

> 
"location" : "Farm",
"xcoordinates" : m,
"ycoordinates" : n,

**Comment by danvolchek** [comment]
Hey @zanderb21, I've made a mod which does this. You can download it here: https://www.nexusmods.com/stardewvalley/mods/1688?.
