### ISSUE TITLE
Children's Dynamic Sprite Loader

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#61]
I have an idea for a mod that utilizes a same kind of concept like "XNBLoader" but instead for player's children's or baby.

> 

    Description:
A mod that loads custom toddler's sprite according to spouse we marry.
Adding more playing exprience.

> 

    How it works:
- Player extracts a toddler sprite mods to this mods "modcontent" folder (can be renamed something else).
- The extracted toddler sprites must be according to available bachelors or bachelorettes.
    + Let's say you've downloaded "Emily's Toddlers" and "Halley's Toddlers"
    + User must extract it at "...\modcontent\Emily" and "...\modcontent\Halley"
- If the player decides to woo their spouse, then mods will try to replace vanilla toddler sprite texture with it's custom texture.
- If they decided to woo Emily, then the mods will load toddler sprite from her folder. If they decided to woo Halley, then it loads from "Halley" folder.

> 

    Optionals:
- I think it's good to add a feature like dynamic sprite-ing (?) that the mod will try to load randomly each day if the player have multiple toddler.xnb files for a certain spouse (can be toggled on or off)
- I think adding this optional would require the mods to write it's own save data.

Thanks in advance

**Comment by Acerbicon** [comment]
This sounds like it would work more like Dynamic Horses or Customize Exterior than XnbLoader, as that simply allows you to load xnbs into the game without overwriting base game files.

**Comment by Warilized** [comment]
Yes it's something like that...
The mod only loads specific sprite if they chose specific spouse...

So player who had multiple saves and different spouse can load different toddler sprite

**Comment by Warilized** [comment]
Maybe this mod could be used as the children's texture, haven't asked it tho
https://rd.nexusmods.com/stardewvalley/mods/626

**Comment by CroiDorcha** [comment]
I'd love to try to develop this if no one has done it yet (and doesn't look like it).

**Comment by CroiDorcha** [comment]
Done: https://www.nexusmods.com/stardewvalley/mods/1756
I hope you like it

**Comment by Warilized** [comment]
Thank you very much for making it CroiDorcha, you rocks
