### ISSUE TITLE
Mod Data Saver

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#62]
A mod that saves (backup) another mod save data to it's own folder. (not too urgent but a nice feature)

> 

	Description:
A mod that back-up every mods that has its own save data so mod user can be relieved when something bad happens with their mods, they can also uninstall mods without feeling losing something.

> 

	Features:
- Saving (or backup-ing) mod that uses its own save data folder/file like "Get Dressed" or "Skill Prestige".
- Mod save data will always be saved to "moddata" folder when you save your game.
- Saving by scanning mod's folders that has "psconfigs", "savedata", "data", (or any other folder, including but optional "i18n" folder), *exception maybe added for something like "XnbLoader", "Custom Farm Types", or "Custom Furniture".
- [Configurable] Option to always reload save data at every game start so any unwanted modification would be avoided, (of course "i18n" folder will be an exception, but it can be set with a toggle).
- [Optional features] For mod developers, devs can reference this mod so it can only save and overwrite its own data to "Mod Data Saver"'s "mod data" folder, and of course also load it (Mod user ofc will need this mod, but i think you could make this optional features).

> 

	Notes:
- I'm not sure that it can work with customized mod file names (not programming naming convetions).
- Maybe it'll works if the mods scan .dll instead? but then again how could the mod knows where to overwrite mod save data files?
- It could be solved maybe with a separate modinfo file containing "mod names", "mod dll", "mod path".

Thanks in advance

**Comment by Pathoschild** [comment]
This would be pretty difficult to do well, and upcoming versions of SMAPI will have an API to store data in the save file to avoid needing local data files. Someone is still welcome to do this if they want, but otherwise I'll close this as won't do.
