### ISSUE TITLE
Fix for 6PM animal happiness drain

### ISSUE THREAD

**Issue by Corverne** [StardewModders/Modding-Ideas#64]
As far as I know, that's the only part of the happiness system that wasn't fixed, and it's unfortunately also the worst bug with it. StarPeanut had a fix that set happiness to 255 every night, but they seem to be inactive, and it isn't compatible with SMAPI 2.0.

Thanks!

**Comment by Pathoschild** [comment]
This should be pretty easy with a SMAPI mod, without needing to set full happiness. For example:
1. Periodically track each animal's happiness.
2. After 6pm, restore an animal's happiness if it decreased since the last check.

**Comment by Corverne** [comment]
Oh yes, I'd love that--then it'd truly reflect how well you care for them! I don't know much about scripting or anything like that, but it sounds great to me!

**Comment by YonKuma** [comment]
I'm going to give this one a shot.

**Comment by Corverne** [comment]
Thanks! :D

**Comment by Warilized** [comment]
Just reporting, this mod has been finished:

https://rd.nexusmods.com/stardewvalley/mods/1597

**Comment by Pathoschild** [comment]
🎉

I updated the [SMAPI 2.0 compatibility list](https://stardewvalleywiki.com/Modding:Updating_mods_for_SMAPI_2.0#SMAPI_mods) to add it as a replacement for Animal Mood Fix and Happy Animals.
