### ISSUE TITLE
Ship from anywhere

### ISSUE THREAD

**Issue by Library-Tech** [StardewModders/Modding-Ideas#65]
Perhaps in tandem with Chests Anywhere, or at least work similarly, but pressing a key (e.g. 's') would open the shipping box and you could place items within for shipping from anywhere rather than having to be standing at the bin on your farm.

**Comment by Pathoschild** [comment]
The upcoming Chests Anywhere 1.12 adds support for the shipping bin. :)

> ![image](https://user-images.githubusercontent.com/230581/32410813-1ae65ac2-c1a0-11e7-96a3-689d3a6ab9a2.png)

**Comment by Entoarox** [comment]
https://www.nexusmods.com/stardewvalley/mods/1379/?

Already a mod, closing this.

**Comment by Library-Tech** [comment]
Awesome! Thanks.
