### ISSUE TITLE
We Need a "Jump"!

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#69]
We need a jump function so we can skip a few stuff like grass and woods...
and also fences.

Sprite for jumping maybe just normal walking sprites. also SFX would be taken from when we ride horses.

**Comment by Entoarox** [comment]
Adding new animations to the farmer is incredibly difficult for multiple reasons (See #63)

**Comment by spacechase0** [comment]
https://www.nexusmods.com/stardewvalley/mods/1844
