### ISSUE TITLE
Multiple horses?

### ISSUE THREAD

**Issue by dgfcx** [StardewModders/Modding-Ideas#70]
I was thinking multiple horses similar to how the more pets mod works, that way you can use a lot of replacements for maybe 10 horses a game.

**Comment by Entoarox** [comment]
A horse-skin mechanic is planned for morePets, but due to how the horse works is currently only "planned" since I've not yet managed to figure out a good way to do it that -fits- the lore.

**Comment by dgfcx** [comment]
I see! Well good luck on it! I have an idea if you’d like suggestions maybe?

**Comment by dgfcx** [comment]
I was thinking is there a possible way to put skins on a dog to look like a horse? I’ve seen people make cats into different animals and dogs have been turned to pigs? So maybe more of a pony then a horse? And I was thinking mayhaps by the Joja mart is where you can find an abandon horse trailer or something? Or you could simply find them in the box like more pets! Thank you for your help and Info!

**Comment by KarBoy2314PL** [comment]
hmm https://www.nexusmods.com/stardewvalley/mods/2274
