### ISSUE TITLE
Cat ears and tail on Abigail

### ISSUE THREAD

**Issue by dgfcx** [StardewModders/Modding-Ideas#71]
I’ve been at it for a few days now trying to add a feline flare to Abby but to no avail. I was trying to add a pair of black ears and black tail (I more used a very dark shade of purple with lilac inner ears) either way I failed miserably, I couldn’t get the lengths, shape or shading well enough that it looked okay, I searched from tons of mods but they all turned out blank except for a portrait mod (which I am using). Someone was working on it and sadly it seems they grew inactive. I was wondering if perhaps someone here could make a mod for it? That would be heavily appreciated.
Nothing sexual either just a cat tail and cat ears. Some tips or recommendations to programs would be appreciated too!

**Comment by dgfcx** [comment]
As a matter of fact I have learned to easily change an xnb to a png that you can edit and the switch back, if you need me to give you the sprite sheet to edit I’d love to!

**Comment by DelightedCat** [comment]
Enjoy! [https://community.playstarbound.com/resources/abigail-cat-costume.5216/](url)

**Comment by Pathoschild** [comment]
@DelightedCat Thanks! I suggest using [Content Patcher](https://www.nexusmods.com/stardewvalley/mods/1915) for new texture mods though. :)
