### ISSUE TITLE
No friendship decay

### ISSUE THREAD

**Issue by Pathoschild** [StardewModders/Modding-Ideas#72]
A SMAPI mod which prevents [friendship points from decaying](https://stardewvalleywiki.com/Friendship#Decay). See the ancient (and no longer compatible) [No Friendship Decay](https://community.playstarbound.com/threads/no-friendship-decay.108278/) mod for example.

**Comment by isaacs-dev** [comment]
Since I'm looking to learn SDV modding, I'll do this one.

**Comment by isaacs-dev** [comment]
I've completed the mod. You can find it [here](https://www.nexusmods.com/stardewvalley/mods/1738?tab=description).

**Comment by Pathoschild** [comment]
Thanks! I updated the [SMAPI compatibility list](https://stardewvalleywiki.com/Modding:SMAPI_compatibility).
