### ISSUE TITLE
Scarecrow that is only 1 tile tall/Scarecrow that is just a stick

### ISSUE THREAD

**Issue by BaconCatBug** [StardewModders/Modding-Ideas#73]
I keep forgetting to water my plants hidden by the scarecrow, I would love a mod that makes it just a stick or doesn't hide the tile above it

**Comment by Fynzou** [comment]
Here ya go: https://www.nexusmods.com/stardewvalley/mods/1803/ Includes two options, one with the scarecrow head only and one with just the stick.

**Comment by Entoarox** [comment]
Completed, closing issue.
