### ISSUE TITLE
Persistent Game Options

### ISSUE THREAD

**Issue by shailalias** [StardewModders/Modding-Ideas#74]
Would it be possible through SMAPI to keep your Game Options (keybinds, controller config, lighting, etc.) persistent between saves? I especially want this for creating new saves. I'd like to be able to save a configuration and have it loaded on any character.

**Comment by Pathoschild** [comment]
That shouldn't be too hard. The mod would...
1. detect when you close the options screen, and save the options to a JSON file;
2. detect when you load a game, and override the options to match the saved settings.

**Comment by shailalias** [comment]
I think I figured out how to make this happen. I'm working on it right now.

**Comment by shailalias** [comment]
This is now complete: https://rd.nexusmods.com/stardewvalley/mods/1778
