### ISSUE TITLE
Remove Ponds from Standard Farm

### ISSUE THREAD

**Issue by BaconCatBug** [StardewModders/Modding-Ideas#76]
I would like to request a SMAPI mod that changes the pond tiles to dirt, and adds a water trough (This one from cooptiles https://prnt.sc/hwi2eo) to the front of the farmhouse, in front of the rightmost stone wall to fill your can. http://prntscr.com/hwi9js

I attempted this myself and failed miserably with Tiled, and even if I had the faintest notion of how to do it via SMAPI I don't have the tools needed to compile the mod. :)

**Comment by Pathoschild** [comment]
This should be pretty straightforward as an XNB mod (editing the standard map) or SMAPI mod (patching it).

**Comment by BaconCatBug** [comment]
I tried making it as an XNB mod but I obviously am doing something wrong
because all it did was cause SDV to crash on load.

I only suggested a SMAPI mod because it would be more compatible.

**Comment by Acerbicon** [comment]
I could do this as an XNB mod fairly quickly, but I wouldn't know how to make it SMAPI capable.

**Comment by Pathoschild** [comment]
Done as an XNB mod: [No Pond Standard Farm](https://www.nexusmods.com/stardewvalley/mods/1751).
