### ISSUE TITLE
Desert Obelisk

### ISSUE THREAD

**Issue by BlatantDecoy** [StardewModders/Modding-Ideas#77]
Add a Desert Obelisk to the Wizards shop, allows quick free travel to the Calico Desert

**Comment by Entoarox** [comment]
Extended minecarts already provides a way to access the desert without needing the bus, and other mods make the bus less expensive.

Adding another way of reaching the desert would just be overkill.

**Comment by Pathoschild** [comment]
Nothing wrong with another option, especially one that fits in with the game's vanilla teleport method.

**Comment by HopeWasHere** [comment]
I think this would be a great mod, it would feel right at home with the other obelisks :)

**Comment by minervamaga** [comment]
![desertobelisk](https://user-images.githubusercontent.com/37347445/38116072-22fa87c4-3374-11e8-91df-63cdb607f4d7.png)
Something like this?  :grin

**Comment by minervamaga** [comment]
![desertwarpstatue](https://user-images.githubusercontent.com/37347445/38119058-9c5d375a-3384-11e8-90d0-bca2bde13a20.png)
![desertwarptotem](https://user-images.githubusercontent.com/37347445/38119059-9c70eba6-3384-11e8-8c2d-50536d660ccd.png)

**Comment by minervamaga** [comment]
![desertobelisk_starblueversion](https://user-images.githubusercontent.com/37347445/38121585-c8c71b7e-3395-11e8-8b8c-53f3d593ee4c.png)
Starblue recolor, as requested

**Comment by minervamaga** [comment]
![desertwarpstatuewithniche](https://user-images.githubusercontent.com/37347445/38157844-784fc428-3450-11e8-9d5d-37c53942965c.png)
More variations!

**Comment by danvolchek** [comment]
Hey @BlatantDecoy, I made a mod which does this: https://www.nexusmods.com/stardewvalley/mods/2021!

It's also Starblue Valley compatible. Currently there is no desert warp totem, but that will be added in the future after the multiplayer update. :)

**Comment by BlatantDecoy** [comment]
Looks really good, glad to see someone implemented it so well. Good job to the both of you
