### ISSUE TITLE
Better Sorting

### ISSUE THREAD

**Issue by GoldDragon7170** [StardewModders/Modding-Ideas#79]
After playing Stardew Valley for a while I noticed that the organization button randomly sorted quality. Is there a way to make it sort with quality? For example, standard, silver, gold, then iridium. And separating colors too. So then it would sort tulips by color then by quality.

**Comment by KarBoy2314PL** [comment]
I'd like to also add something on top of that - to allow the player to choose the sorting order of tools.
I"m used to have a sword on 1 and pickaxe on 2, but the sort button does the complete opposite, which is annoying for me.

**Comment by Warilized** [comment]
I'd like to also add some feature, that is "order by"...

So you can order by Default, Variation(color, etc.), Quality, Type, Alphabetical

**Comment by Riazaia** [comment]
[Better Sort](https://www.nexusmods.com/stardewvalley/mods/1992) can do this ))
