### ISSUE TITLE
Junimos Harvest Fruit Trees

### ISSUE THREAD

**Issue by MsMeiriona** [StardewModders/Modding-Ideas#82]
Junimos currently don't harvest your fruit trees, only crops.

**Comment by Entoarox** [comment]
Not having spend a lot of time in the jumino or fruit tree code, I dont know how difficult this would be.

**Comment by danvolchek** [comment]
I've added this feature to one of my mods: https://www.nexusmods.com/stardewvalley/mods/1976. :)
