### ISSUE TITLE
A remake of Reusable Wallpapers and Floors

### ISSUE THREAD

**Issue by KnittingCounter** [StardewModders/Modding-Ideas#87]
Hey folks. I go online by Jokerine and was told to post this here :)

A mod I really like, "Reusable Wallpapers and Floors" by Iceburg, broke during one of the latest SMAPI updates and it hasn't been possible to update it. I just can't play without it and it makes me so sad that the poor thing has been left to rot...

Here is the page for anyone curious. https://www.nexusmods.com/stardewvalley/mods/356/?

So, I was wondering if anyone skilled would've been up for remaking it. I know that the idea is sorta redundant now with the catalog that was added to the game but I really miss this mod which made it much more convenient and - dare I say it - immersive for me.

The idea of the mod is really simple - whenever you replace a wallpaper or floor in your house, you get back the old one, instead of it disappearing forever.

If anyone would be up for this it would make me the happiest farmer in all of Pelican! Thank you and fingers crossed!

**Comment by Mizzion** [comment]
Here you are. Its basically the same thing as the original. The only differences are that:

1. It works with SMAPI 2.4
2. It has a config file that you can enable or disable in-game messages.

https://www.nexusmods.com/stardewvalley/mods/1905/

**Comment by KnittingCounter** [comment]
Oh wow, I really never thought this would get picked up! Thank you so much, @Mizzion , you're a star! <3

**Comment by Mizzion** [comment]
You're quite welcome.
