### ISSUE TITLE
XNB/Building Sprite Manager

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#89]
Just like its name, its manages building sprites in-game (I'm assuming it is feasible).
It works closely like [Portraiture mod](https://rd.nexusmods.com/stardewvalley/mods/999) i think.

The Idea is to make the mod handles drawing game sprites into the game. The user can adds several XNB mod of the same building, and then choose it in-game via some sort of interface/setting.

Example of location:
>".../BldSprtmgrmod/assets/Building/Mill/..."
 

The mod of course can save player preferences each saves, saving player from the hurdle of switching XNB mods...

This mod may also works to manage character sprites so player can adds several sprites and choose what he wants at the time, if the developer desires of course. but I think the interface will have several tabs like "Building", "Character", etc.

Also it'll be nice if the mods can draw cursor from "cursor.xnb" separately, so player can have multiple cursor without affecting the original sprites that is inside the default XNB.

I think making XNBLoader have this option is great, but then the devs had to rewrite their codes to make it works.

**Comment by Entoarox** [comment]
Mod already exists, closing this as complete: https://rd.nexusmods.com/stardewvalley/mods/1099
