### ISSUE TITLE
Cursor sprite changer

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#90]
Changing the game cursor is a little bit tricky, because in Cursor.xnb have loads of other thing than just cursor...
So if you like a certain cursor, but there's another mod conflicting it, you just edit it and fuse it together, which is a little time consuming and undesirable.

So instead drawing the cursor sprite from default cursor.XNB, the mods instead draws from its own folder to draw the cursor.

So player can freely change their cursor, without changing their original/default Cursor.xnb files

**Comment by Pathoschild** [comment]
SMAPI lets multiple mods to edit the loaded `cursors.xnb` spritesheet without changing the file itself. A mod could easily load a cursor PNG from its folder and edit it into `cursors.xnb` at runtime.

**Comment by Warilized** [comment]
can it be an XNB file instead of PNG?

**Comment by Pathoschild** [comment]
Sure, SMAPI supports both. It'd be up to the mod developer how they implement it.

**Comment by EpicBellyFlop45** [comment]
I'll start working on that when I get back from work today

**Comment by EpicBellyFlop45** [comment]
https://www.nexusmods.com/stardewvalley/mods/3014 There you go

**Comment by Warilized** [comment]
I made it myself. Thank Andy for assigning this mod, i forgot about this haha...

Anyway here's the link:

https://www.nexusmods.com/stardewvalley/mods/3694
Uses Custom Patcher
