### ISSUE TITLE
Fruit Tree Production

### ISSUE THREAD

**Issue by RussRod96** [StardewModders/Modding-Ideas#91]
Hi, I was wondering if there was anyone who would be able or willing or both to create or add to CJB Cheat Menu to speed up the production of fruit trees, please and thank you ~Russ

**Comment by Mizzion** [comment]
Here you go. There is an option under the machine section all the way at the bottom that will enable fast fruit trees.

[CJBCheatsMenu 1.17.1-Mizzion-update.zip](https://github.com/StardewModders/Modding-Ideas/files/1743117/CJBCheatsMenu.1.17.1-Mizzion-update.zip)

**Comment by Pathoschild** [comment]
@Mizzion Feel free to submit a pull request to the [CJB mods repo](https://github.com/CJBok/SDV-Mods) if you want to add it to the official version. :)

**Comment by Pathoschild** [comment]
Added to CJB Cheats Menu in the next release. Thanks!

**Comment by Mizzion** [comment]
Not a problem at all.
