### ISSUE TITLE
Current Location Popup, upgrade?

### ISSUE THREAD

**Issue by Warilized** [StardewModders/Modding-Ideas#92]
Are there perhaps someone want to upgrade "Current Location" Mod?
https://www.nexusmods.com/stardewvalley/mods/638

I'm just asking if there's any modder willing to upgrade this good mod (imo) to be better
Currently this mod lacking in accuracy of the location names, as its only use game's reference like "Forest" not the actual name "Cindersap Forrest".
And also it's lacking in translation compatibility...

thanks~

**Comment by Mizzion** [comment]
Here you are. The map names are based on the official wiki's names. Any errors let me know. It's also fully translatable.

https://www.nexusmods.com/stardewvalley/mods/1929/

**Comment by Warilized** [comment]
Thank you very much~
I will tell you if there's any bug present
