### ISSUE TITLE
Make friendship challenge?

### ISSUE THREAD

**Issue by hfgenman0601** [StardewModders/Modding-Ideas#93]
vanilla friendship decay 2 if not speak.
It is easy to make an NPC full hearts in less than 2 month.

https://community.playstarbound.com/resources/4435
This mod provides a way that friend ship decay faster if you don't give them a gift ,especially on birthday.

But unfortunately,this mod no longer support latest SMAPI,so is there anyone could help me to make this running?

**Comment by Mizzion** [comment]
Here you go, I've made this mod as close to the one you requested as possible. The main difference is that it has 8 different Dialogues that the NPC's can use. All you need to do is unzip the folder into your Stardew Valley/Mods folder.


Any errors or bugs, feel free to message me about it, and i'll get them fixed.

[EnhancedRelationships.zip](https://github.com/StardewModders/Modding-Ideas/files/1762456/EnhancedRelationships.zip)

**Comment by Pathoschild** [comment]
Why not release the mod on Nexus? :)

**Comment by Mizzion** [comment]
It's on there :) Just not published yet, I finished it when I got home from work, I just have to finish the description, then it'll be published.

**Comment by Pathoschild** [comment]
(See [EnhancedRelationships on Nexus](https://www.nexusmods.com/stardewvalley/mods/1927).)
