### ISSUE TITLE
Activating Sprinklers up for anyone who wants to maintain it.

### ISSUE THREAD

**Issue by Heartwerk** [StardewModders/Modding-Ideas#95]
PhthaloBlue is no longer maintaining [Activating Sprinklers](https://github.com/lambui/StardewValleyMod_ActivatingSprinklers). It's now open source for anyone who wants to keep the mod up to date, with the code and license at the link. PathosChild recommended I post this here.

I'm no coder, I don't know what work that'd take, but Phthalo said it "should be an easy task since it's fairly simple."

One thing I'll note for whoever wants to keep it going is that it'd be great if this could be made compatible with the Better Sprinklers/SMAPI Sprinklers mod! Right now it seems to work mostly OK with my game, but only covers the default sprinkler range. Sometimes it covers a greater range but never the full Better Sprinklers range, and it'll usually be a rectangular box in the direction my character is facing.

I hope someone'll take this on, personally it does something I've wanted in-game for a long time, and it'd be great if it could be brought back up to speed!

**Comment by Pathoschild** [comment]
Better Sprinklers has a mod API available which returns sprinkler radius, so that integration would be pretty straightforward. (See [Data Maps' integrations](https://github.com/Pathoschild/StardewMods/tree/develop/Common/Integrations) for an example.)

**Comment by f4iTh** [comment]
I could possibly take the opportunity, but I'd need some guidance in taking advantage of the Better Sprinklers mod API (and/or taking advantage of mod APIs in general) to integrate it with this mod

**Comment by Pathoschild** [comment]
Feel free to ask me on Discord. :)

**Comment by Mizzion** [comment]
Since f4iTh seems to be pretty busy, you can use this one until they get theirs released. This version will work with either Better Sprinklers or Simple Sprinklers activated. 
[ActivateSprinklers 1.0.zip](https://github.com/StardewModders/Modding-Ideas/files/1822572/ActivateSprinklers.1.0.zip)

**Comment by f4iTh** [comment]
Sorry for taking so long, ~~I totally didn't forget all about it~~. It's released now so there's that.
[Mod page is right over here.](https://www.nexusmods.com/stardewvalley/mods/2088/)
