### ISSUE TITLE
Transmute Gold bars to Iron and Iron to Copper

### ISSUE THREAD

**Issue by Danny3989** [StardewModders/Modding-Ideas#98]
A mod to add a recipe that lets you transmute Gold bars into Iron and Iron to Copper so that way all this Gold isn't sitting here and has more use to make it into kegs and such.

**Comment by HopeWasHere** [comment]
Do you mean something like this? https://www.nexusmods.com/stardewvalley/mods/1054
It's not a recipe, but it does let you turn gold into iron and iron into copper

**Comment by f4iTh** [comment]
![screenshot_1299](https://user-images.githubusercontent.com/34132723/39667823-b80a213e-50c6-11e8-8221-01d13b6048df.png)
This seems to work fine over here
