### ISSUE TITLE
Simulate time after sleeping

### ISSUE THREAD

**Issue by spacechase0** [StardewModders/Modding-Ideas#99]
Simulate game time ticks after you sleep, up until a certain point, (12:00? 2:00? 6:00?), so that machines will still function as if time passed when you sleep.

Currently, vanilla machines do account for the time, but mod functions such as Automate cannot hook into it properly to make things process as many things overnight as the time allows.

**Comment by Platonymous** [comment]
Try this and let me know if it works.

[PYTK_0_8_4b_SleepWorker_1_0_0b.zip](https://github.com/StardewModders/Modding-Ideas/files/1922483/PYTK_0_8_4b_SleepWorker_1_0_0b.zip)

Skipping time freezes the game for a moment, and skipping past 19:50 will greet you with an "It's getting late" message in the morning. I might find a better solution down the road, but for now the default settings are set to skip 5h max and not past 19:50. You can change them in the config.json if you want to skip longer or more hours.

**Comment by Platonymous** [comment]
https://www.nexusmods.com/stardewvalley/mods/2062/
